@startuml
'https://plantuml.com/class-diagram

class Drink {
    -int kind
    {static} +int COKE
    {static} +int DIET_COKE
    {static} +int TEA
    +int getKind()
}

class VendingMachine {
    ~int quantityOfCoke
    ~int quantityOfDietCoke
    ~int quantityOfTea
    ~int numberOf100Yen
    ~int charge
    +Drink buy(int i, int kindOfDrink)
    +int refund()
}

Drink <.. VendingMachine


@enduml